create table author (
    id integer generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table book (
    id integer generated by default as identity,
    title varchar(255),
    author_id integer,
    primary key (id)
);
create table book_library (
    book_id integer not null,
    library_id integer not null
);
create table library (
    id integer generated by default as identity,
    street varchar(255),
    name varchar(255),
    primary key (id)
);

alter table book
    add constraint FKklnrv3weler2ftkweewlky958
    foreign key (author_id) references author;

alter table book_library
    add constraint FK8h55xcx6uxadt03tnas6mjmhf
    foreign key (library_id) references library;

alter table book_library
    add constraint FKl0etqx9njpgs32v9drfsv7l4k
    foreign key (book_id) references book;